version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: pylint bulk_download.py

workflows:
  main:
    jobs:
      - build-and-lint
